Add ERB Support for SQL definitions
teoljungberg/fx pull request #98
Opened 2022-12-24 18:44 UTC by gmhawash

Allow for ERB interpolation in SQL definition files.  This is helpful when SQL definition relies on some ruby constants or methods.

2023-01-21 12:06 UTC, teoljungberg commented
I have never seen this in real life practice, can you cite a project or two that uses this?

2023-01-23 14:13 UTC, gmhawash commented
Our application uses a private gem that exposes a set of transaction codes.  Every once in a while we update the gem (based on customer requirements) and the transaction codes are used in SQL functions, views and queries.  So for us, rather than listing the transactions codes all over the place; we do this inside these SQL entities:

```
SELECT ....
WHERE transactions.code  IN (<%= TransactionGem.payment_codes.join(',') %>) OR transactions.code in (<%= TransactionGem.jouranl_entry_codes.join(',') %>)
```

And when we update the transaction gem; we just rerun the migration to recreate the SQL functions and views and that updates them properly.

2023-01-24 12:29 UTC, teoljungberg commented
I see! Thanks for context.

I'm going through a maintenance of the project to cut out old and stale versions of ruby and rails. And will cut a release for that before I come back to this.

2023-03-18 16:14 UTC, teoljungberg commented on lib/fx/version.rb
> +  VERSION = "1.7.1"
You don't need to change this, I'll do that once a release is ready.

```suggestion
  VERSION = "0.7.0"
```

Or to be on top of master

```suggestion
  VERSION = "0.8.0"
```

2023-03-18 16:14 UTC, teoljungberg commented on spec/fx/definition_spec.rb
> +            CREATE OR REPLACE FUNCTION test()
Swap this to 2 space indentation

2023-03-18 16:14 UTC, teoljungberg commented on spec/fx/definition_spec.rb
> +            $$ LANGUAGE plpgsql;
```suggestion
          CREATE OR REPLACE FUNCTION test()
          RETURNS text AS $$
          BEGIN
              RETURN 'test';
          END;
          $$ LANGUAGE plpgsql;
          CREATE OR REPLACE FUNCTION west()
          RETURNS text AS $$
          BEGIN
              RETURN 'west';
          END;
          $$ LANGUAGE plpgsql;
```

2023-03-21 13:06 UTC, gmhawash commented
I pushed a commit to resolve these issues.

2023-03-23 07:46 UTC, teoljungberg approved these changes

2023-03-23 07:46 UTC, teoljungberg commented on spec/fx/definition_spec.rb
> -              RETURN 'test';
Thanks for fixing these too 👏🏻

2023-03-23 07:46 UTC, teoljungberg commented on spec/fx/definition_spec.rb
> +        expect(definition.to_sql.delete("\n").squeeze(' ').strip).to eq erb_sql_definition
This expectation is more than a mouthful to read. Not a blocker for now, but I'll take a stab at reformatting it to make it leaner and meaner

2023-03-23 07:48 UTC, teoljungberg commented
I ran CI @gmhawash - and there are some `standardrb` fixes to be made before we merge this.

2023-03-25 09:07 UTC, teoljungberg requested changes
As mentioned above - CI is failing.

2023-03-25 14:08 UTC, gmhawash commented
When I run this locally everything passes.  What do I need to do to make it fail locally so I can fix these issues?

2023-03-25 15:12 UTC, teoljungberg commented
@gmhawash it’s because your local version of standard.rb is out of date with ci

2023-03-26 08:34 UTC, teoljungberg commented on spec/fx/definition_spec.rb
> +        definition = Fx::Definition.new(name: "test", version: 1)
```suggestion
        definition = Fx::Definition.function(name: "test", version: 1)
```

AS this was changed on master with #119

2023-03-26 08:34 UTC, teoljungberg commented on spec/fx/definition_spec.rb
> +
```suggestion
```

2023-03-26 08:36 UTC, teoljungberg requested changes

2023-03-26 08:36 UTC, teoljungberg commented on lib/fx/definition.rb
> +      @version = latest_version if @version == :latest
This feels unrealted to this PR?

2023-03-26 08:44 UTC, teoljungberg commented
Having thought about this more from a consistency perspective, this change would make the database migration non-reversible as the evaluated code with ERB can and will probably change.

I would be surprised if that happened to me, and therefore don't want to include that uncertainty.

More reasoning along the same lines from fx's sister project scenic:
https://github.com/scenic-views/scenic/issues/248

2023-03-26 08:44 UTC, closed without merging